name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Install cargo deb
      run: cargo install cargo-deb
    - name: Install build dependencies
      run: sudo apt-get install -y pkg-config libsqlite3-dev libssl-dev libclang-dev
    - name: Build
      run: cargo build
    - name: Package
      run: cargo deb && cargo deb --variant srv
    - name: Run tests
      run: cargo test
    - name: Publish
      uses: svenstaro/upload-release-action@2.9.0
      with:
        file: target/debian/*.deb
        file_glob: true
        overwrite: true
        tag: dev
