name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest-arm]
      

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Install cargo deb
      run: cargo install cargo-deb
    - name: Install build dependencies
      run: sudo apt-get install -y pkg-config libsqlite3-dev libclang-dev 
    - name: Build
      run: cargo build
    - name: Package
      run: cargo deb
    - name: Run tests
      run: cargo test
